/*
 * JwagMain.java
 *
 * Created on 03 June 2007, 16:42
 */

package com.jwag.gui;

import com.jwag.bean.ConnectDB;
import com.jwag.bean.DataSourceDataHolder;
import com.jwag.gen.ApplicationContextGenerator;
import com.jwag.gen.ControllerGenerator;
import com.jwag.gen.BeanGenerator;
import com.jwag.gen.DaoGenerator;
import com.jwag.gen.IndexJspGenerator;
import com.jwag.gen.JspGenerator;
import com.jwag.gen.WebXmlGenerator;
import com.jwag.db.DBConnection;
import java.io.File;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JFrame;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;
import com.sun.java.swing.plaf.motif.MotifLookAndFeel;

/**
 * @author  Saifo
 */
public class JwagMain extends javax.swing.JFrame {
    
    private Connection connection;
    
    /**
     * Creates new form JwagMain
     */
    public JwagMain() {
        File f = new File("src/com/jwag/images/jwagLogo.jpg");
        path = f.getAbsolutePath();
        
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txt_hostname = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txt_dbport = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txt_dbname = new javax.swing.JTextField();
        txt_dbusername = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btn_DBconnect = new javax.swing.JButton();
        btn_disconnect = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        txt_dbpassword = new javax.swing.JPasswordField();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        combo_dbtables = new javax.swing.JComboBox();
        jPanel4 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        txt_packagename = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtAppName = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        btn_addall = new javax.swing.JButton();
        btn_removeall = new javax.swing.JButton();
        btn_remove = new javax.swing.JButton();
        btn_add = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        list_all_columns = new javax.swing.JList();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        list_selected_columns = new javax.swing.JList();
        btn_close = new javax.swing.JButton();
        btnGenerator = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTAMessages = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        jLabel13 = jLabel13 = new JLabel("", new ImageIcon(path), JLabel.CENTER);
        jMenuBar6 = new javax.swing.JMenuBar();
        jMenu11 = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        jSeparator21 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle(":: JWAG :: Java Web Application Generator");
        setBackground(new java.awt.Color(230, 222, 199));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Connect to MySQL Database"));

        jLabel1.setText("MySQL Host Address  ");

        txt_hostname.setToolTipText("Specify host name or IP Address of the Server");

        jLabel2.setText("Port:");

        txt_dbport.setToolTipText("Define a TCP/IP port for connecting to the database");

        jLabel3.setText("Database:");

        txt_dbusername.setToolTipText("Specify a user name for connecting to the database server");

        jLabel4.setText("User Name");

        jLabel5.setText("Password:");

        btn_DBconnect.setText("Connect");
        btn_DBconnect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_DBconnectActionPerformed(evt);
            }
        });

        btn_disconnect.setText("Disconnect");
        btn_disconnect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_disconnectActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 2, 11));
        jLabel10.setText("For Example : 127.0.0.1 or use host name ");

        jLabel12.setFont(new java.awt.Font("Tahoma", 2, 11));
        jLabel12.setText("Provide User Name for connecting to Database");

        jLabel16.setFont(new java.awt.Font("Tahoma", 2, 11));
        jLabel16.setText("Provide MySQL user password");

        jLabel17.setFont(new java.awt.Font("Tahoma", 2, 11));
        jLabel17.setText("TCP/IP port for connecting to the database");
        jLabel17.setToolTipText("Define a TCP/IP port for connecting to the database server");

        jLabel18.setFont(new java.awt.Font("Tahoma", 2, 11));
        jLabel18.setText("Provide Database name");

        org.jdesktop.layout.GroupLayout jPanel2Layout = new org.jdesktop.layout.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabel1)
                    .add(jLabel4)
                    .add(jLabel5)
                    .add(jLabel3)
                    .add(jLabel2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 32, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(txt_dbname)
                    .add(txt_dbusername)
                    .add(txt_hostname, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                    .add(txt_dbpassword, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 92, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(txt_dbport, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 49, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(25, 25, 25)
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, btn_disconnect, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 119, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jPanel2Layout.createSequentialGroup()
                        .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jLabel12)
                            .add(jLabel10)
                            .add(jLabel16)
                            .add(jLabel17, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 218, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 56, Short.MAX_VALUE))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel2Layout.createSequentialGroup()
                        .add(jLabel18, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 148, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 14, Short.MAX_VALUE)
                        .add(btn_DBconnect, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 119, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel2Layout.createSequentialGroup()
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel1)
                    .add(txt_hostname, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel10, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 20, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel4)
                    .add(txt_dbusername, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel12))
                .add(6, 6, 6)
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel5)
                    .add(jLabel16)
                    .add(txt_dbpassword, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 23, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel17)
                    .add(jLabel2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 19, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(txt_dbport, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(btn_DBconnect)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(btn_disconnect))
                    .add(jPanel2Layout.createSequentialGroup()
                        .add(19, 19, 19)
                        .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jLabel3)
                            .add(jLabel18)
                            .add(txt_dbname, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Select Table For Generating The Code"));

        jLabel7.setText("Select Table:");

        combo_dbtables.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select Table" }));
        combo_dbtables.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                combo_dbtablesItemStateChanged(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPanel3Layout = new org.jdesktop.layout.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .add(jLabel7, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 84, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(combo_dbtables, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 160, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(293, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(combo_dbtables, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel7))
                .addContainerGap())
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Application Configuration"));

        jLabel6.setText("Package Name:");

        txt_packagename.setText("com.project");
        txt_packagename.setToolTipText("Provide the project package Name. Like com.project.my");

        jLabel14.setText("Application Name :");

        txtAppName.setToolTipText("Provide the application name for Generating the code");

        org.jdesktop.layout.GroupLayout jPanel4Layout = new org.jdesktop.layout.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel4Layout.createSequentialGroup()
                .add(jLabel14)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(txtAppName, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 137, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 56, Short.MAX_VALUE)
                .add(jLabel6)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(txt_packagename, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 139, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(48, 48, 48))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel4Layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .add(jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel14)
                    .add(txtAppName, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel6)
                    .add(txt_packagename, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 19, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btn_addall.setText(">>");
        btn_addall.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addallActionPerformed(evt);
            }
        });

        btn_removeall.setText("<<");
        btn_removeall.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_removeallActionPerformed(evt);
            }
        });

        btn_remove.setText("<");
        btn_remove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_removeActionPerformed(evt);
            }
        });

        btn_add.setText(">");
        btn_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addActionPerformed(evt);
            }
        });

        jLabel8.setText("All Columns");

        jScrollPane1.setViewportView(list_all_columns);

        jLabel9.setText("Columns select for the view");

        jScrollPane2.setViewportView(list_selected_columns);

        btn_close.setText("  Quit   ");
        btn_close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_closeActionPerformed(evt);
            }
        });

        btnGenerator.setText("Generate");
        btnGenerator.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGeneratorActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPanel5Layout = new org.jdesktop.layout.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel5Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel5Layout.createSequentialGroup()
                        .add(jPanel5Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, btn_close, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE))
                        .add(41, 41, 41)
                        .add(jPanel5Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                            .add(btn_remove, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, btn_addall, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, btn_removeall, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .add(btn_add, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 91, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                    .add(jLabel8))
                .add(45, 45, 45)
                .add(jPanel5Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(jLabel9)
                    .add(jScrollPane2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                    .add(btnGenerator, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(54, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel5Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel5Layout.createSequentialGroup()
                        .add(jPanel5Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jLabel9)
                            .add(jLabel8))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jPanel5Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jScrollPane2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE)
                            .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jPanel5Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(btnGenerator, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 23, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(btn_close))
                        .addContainerGap())
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel5Layout.createSequentialGroup()
                        .add(btn_add)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(btn_remove)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(btn_addall)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(btn_removeall)
                        .add(61, 61, 61))))
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel11.setText("Status Bar");
        jLabel11.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        org.jdesktop.layout.GroupLayout jPanel6Layout = new org.jdesktop.layout.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel6Layout.createSequentialGroup()
                .add(jLabel11, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 64, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(761, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel6Layout.createSequentialGroup()
                .add(jLabel11, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel7.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jTAMessages.setColumns(20);
        jTAMessages.setEditable(false);
        jTAMessages.setRows(5);
        jScrollPane3.setViewportView(jTAMessages);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/jwag/images/jwagLogo.jpg"))); // NOI18N
        jLabel13.setToolTipText("JWAG - Code Generator Logo");
        jLabel13.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .add(35, 35, 35)
                .add(jLabel13)
                .addContainerGap(31, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .add(24, 24, 24)
                .add(jLabel13)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        org.jdesktop.layout.GroupLayout jPanel7Layout = new org.jdesktop.layout.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel7Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, jScrollPane3, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 236, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jScrollPane3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 425, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jMenu11.setText("File");
        jMenu11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu11ActionPerformed(evt);
            }
        });

        jMenuItem6.setText("Exit");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu11.add(jMenuItem6);
        jMenu11.add(jSeparator21);

        jMenuBar6.add(jMenu11);

        setJMenuBar(jMenuBar6);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(jPanel7, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jPanel5, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .add(jPanel4, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .add(jPanel3, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .add(jPanel2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .add(jPanel6, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(jPanel2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jPanel3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jPanel4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jPanel5, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(jPanel7, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel6, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 20, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenu11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu11ActionPerformed
// TODO add your handling code here:
    }//GEN-LAST:event_jMenu11ActionPerformed
    
    private void ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ActionPerformed
        
//        Object source = evt.getSource();
//        String plaf = "";
//        if (source == metaradiobutton) {
//            plaf = "javax.swing.plaf.metal.MetalLookAndFeel";
//        } else if (source == motifradiobutton) {
//            plaf = "com.sun.java.swing.plaf.motif.MotifLookAndFeel";
//        } else if (source == windowsradiobutton) {
//            plaf = "com.sun.java.swing.plaf.windows.WindowsLookAndFeel";
//        } else if (source == windowClassic) {
//
//            plaf = "com.sun.java.swing.plaf.windows.WindowsClassicLookAndFeel";
//        }
//        try {
//            UIManager.setLookAndFeel(plaf);
//            SwingUtilities.updateComponentTreeUI(this);
//        } catch (Exception e) {
//
//            System.out.println("Exception occur in set LookAndFeel : " + e);
//        }
    }//GEN-LAST:event_ActionPerformed
    
    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
setVisible(false);
        dispose();// TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed
    
    private void btnGeneratorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGeneratorActionPerformed
        
        columnNames = new ArrayList<String>();
        projectPackage = txt_packagename.getText().trim();
        applicationName = txtAppName.getText().trim();
        
        if (list_selected_columns.getModel().getSize() > 0) {
            
            for (int i = 0; i < list_selected_columns.getModel().getSize(); i++) {
                
                columnNames.add(list_selected_columns.getModel().getElementAt(i).toString());
            }
            if (columnNames.contains("id")) {
            } else {
                
                for (int j = 0; j < list_all_columns.getModel().getSize(); j++) {
                    
                    if (list_all_columns.getModel().getElementAt(j).toString().equalsIgnoreCase("id")) {
                        
                        columnNames.add(list_all_columns.getModel().getElementAt(j).toString());
                        System.out.println("id added into columnNames");
                    }
                }
            }
            
            ArrayList<String> jspnames = new ArrayList<String>();
            ArrayList<String> daonames = new ArrayList<String>();
            ArrayList<String> controlname = new ArrayList<String>();
            
            
            
            try {
                
                DaoGenerator daoGen = new DaoGenerator();
                JspGenerator jspGen = new JspGenerator();
                BeanGenerator beanGen = new BeanGenerator();
                WebXmlGenerator webxmlGen = new WebXmlGenerator();
                ControllerGenerator controllerGen = new ControllerGenerator();
                IndexJspGenerator indexJspGen = new IndexJspGenerator();
                applicationContextGen = new ApplicationContextGenerator();
                
                /****** Generating a bean ****/
                String beanName = beanGen.generate(tableName, projectPackage);
                System.out.println("bean generated");
                
                jTAMessages.append("\n*************************************\n");
                jTAMessages.append("Bean File is Generated\n");
                jTAMessages.append("*************************************\n");
                /****************************************/
                
                /********* Generating WebXml file *****/
                webxmlGen.generate();
                jTAMessages.append("\n*************************************\n");
                jTAMessages.append("web.xml is Generated \n");
                jTAMessages.append("*************************************\n");
                
                System.out.println("webxml Generated");
                /****************************************/
                
                /****** Generating a jsp files ****/
                jspnames = jspGen.generate(beanName, tableName);
                jTAMessages.append("\n*************************************\n");
                jTAMessages.append("Generating Java Server Pages \n");
                jTAMessages.append("*************************************\n");
                for(String jsp : jspnames){
                    
                    jTAMessages.append("\n "+jsp+".jsp \n");
                    
                }
                //jTAMessages.append("*************************************\n");
                /****************************************/
                
                /****** Generating a Dao files ****/
                daonames = daoGen.generate(tableName, projectPackage);
                System.out.println("daos Generated");
                jTAMessages.append("\n*************************************\n");
                jTAMessages.append("DAO Stuff Generated \n");
                jTAMessages.append("*************************************\n");
                
                
                for(String dao : daonames){
                    
                    jTAMessages.append(" "+dao+".java \n");
                }
                //jTAMessages.append("*************************************\n");
                /****************************************/
                
                /****** Generating a jsp files ****/
                controlname = controllerGen.generate(tableName, jspnames, daonames, projectPackage);
                System.out.println("Controller Generated");
                
                 jTAMessages.append("\n*************************************\n");
                jTAMessages.append("Controller Generated \n");
                jTAMessages.append("*************************************\n");
                
                for(String controller : controlname){
                    
                    jTAMessages.append(" "+controller+".java \n");
                }
                //jTAMessages.append("_____________________________________\n");
                /****************************************/
                
                
                /********* Generating ApplicationContext *****/
                applicationContextGen.generate(tableName, jspnames, dsDataHolder, daonames, controlname, projectPackage);
                
                jTAMessages.append("\n*************************************\n");
                jTAMessages.append("Spring Application Context Generated \n");
                jTAMessages.append("*************************************\n");
                
                
                /****************************************/
                
                /********* Generating index.jsp *****/
                indexJspGen.generate(tableName);
                jTAMessages.append("\n*************************************\n");
                jTAMessages.append("index.jsp Generated \n");
                jTAMessages.append("*************************************\n");
                /****************************************/
                JOptionPane.showMessageDialog(null, "All Files are Generated Successfully", "Information", JOptionPane.INFORMATION_MESSAGE);
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, " "+ex.getStackTrace(), "Alert", JOptionPane.ERROR_MESSAGE);
                
                System.out.println("Exception in Calling GenerateClass Method : " + ex.getMessage());
            }
        } else {
            
            JOptionPane.showMessageDialog(null, "You haven't selected Column for List View Page", "Alert", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnGeneratorActionPerformed
    
    private void btn_closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_closeActionPerformed
        
        setVisible(false);
        dispose();
    }//GEN-LAST:event_btn_closeActionPerformed
    
    private void btn_removeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_removeActionPerformed
        
        if (!list_selected_columns.isSelectionEmpty()) {
            
            String selected_field = "";
            
            selected_field = String.valueOf(list_selected_columns.getSelectedValue());
            
            list2Model.remove(list_selected_columns.getSelectedIndex());
            
            if (listModel.size() == 0) {
                
                listModel.addElement(selected_field);
            } else {
                
                int indexsize = listModel.getSize();
                listModel.add(indexsize++, selected_field);
            } //else
        } else {
            
            JOptionPane.showMessageDialog(null, "You haven't select the field yet", "Alert", JOptionPane.INFORMATION_MESSAGE);
        } //else
    }//GEN-LAST:event_btn_removeActionPerformed
    
    private void btn_removeallActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_removeallActionPerformed
        
        ArrayList arr_selected_col = new ArrayList();
        
        if (list_selected_columns.getModel().getSize() != 0) {
            
            for (int i = 0; i < list2Model.getSize(); i++) {
                
                arr_selected_col.add(list2Model.getElementAt(i));
            } // for
            list2Model.removeAllElements();
            
            for (int j = 0; j < arr_selected_col.size(); j++) {
                
                listModel.add(j, arr_selected_col.get(j));
            } //for
        } else {
            
            JOptionPane.showMessageDialog(null, "Selected Fields List is Empty", "Alert", JOptionPane.INFORMATION_MESSAGE);
        } //else
    }//GEN-LAST:event_btn_removeallActionPerformed
    
    private void btn_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addActionPerformed
        
        if (!list_all_columns.isSelectionEmpty()) {
            
            String selected_field = "";
            selected_field = String.valueOf(list_all_columns.getSelectedValue());
            listModel.remove(list_all_columns.getSelectedIndex());
            
            if (list2Model.getSize() == 0) {
                
                list2Model.addElement(selected_field);
            } else {
                
                int indexsize = list2Model.getSize();
                list2Model.add(indexsize++, selected_field);
            } //else
        } else {
            
            JOptionPane.showMessageDialog(null, "You haven't select the field yet", "Alert", JOptionPane.INFORMATION_MESSAGE);
        } //else
    }//GEN-LAST:event_btn_addActionPerformed
    
    private void btn_addallActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addallActionPerformed
        
        ArrayList arr_columnlist = new ArrayList();
        
        if (list_all_columns.getModel().getSize() != 0) {
            
            for (int i = 0; i < listModel.getSize(); i++) {
                
                arr_columnlist.add(listModel.getElementAt(i));
            } // for
            listModel.removeAllElements();
            
            for (int j = 0; j < arr_columnlist.size(); j++) {
                
                list2Model.add(j, arr_columnlist.get(j));
            } //for
        } else {
            JOptionPane.showMessageDialog(null, "List is Empty", "Alert", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btn_addallActionPerformed
    
    private void btn_disconnectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_disconnectActionPerformed
        
        if (!btn_DBconnect.isEnabled()) {
            setTextFieldsEditable(true);
            
            try {
                
                listModel.clear();
                combo_dbtables.removeAllItems();
                DBConnection.closeConnection(DBConnection.connObject);
                tableName = null;
                columnNames = null;
            } catch (Exception ex) {
                
                System.out.println("Exception on Disconnect :" + ex.toString());
            } //catch
        } //if
    }//GEN-LAST:event_btn_disconnectActionPerformed
    
    private void combo_dbtablesItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_combo_dbtablesItemStateChanged
        
        if (comboBoxModel.getSize() > 0) {
            
            tableName = combo_dbtables.getSelectedItem().toString();
            
            dbmetadata = new com.jwag.db.DatabaseMetaData();
            
            listModel = new DefaultListModel();
            list_all_columns.setModel(listModel);
            
            try {
                
                List<String> column_metadata = dbmetadata.getColumnsName(tableName);
                
                for (String columName : column_metadata) {
                    
                    listModel.addElement(columName);
                }
            } catch (SQLException sqlex) {
                
                System.out.println("Exception Occur in Loading Columns : " + sqlex.getMessage());
            }
            try {
                boolean value = dbmetadata.hasPrimaryKey(tableName);
                System.out.println("boolean value " + value);
                
                if (value) {
                    System.out.println("boolean value " + value);
                    btnGenerator.setEnabled(true);
                } else {
                    btnGenerator.setEnabled(false);
                }
            } catch (SQLException ex) {
                
                System.out.println("Exception Occur in Primary Key Checking : " + ex.getMessage());
            }
        } // if
        list2Model = new DefaultListModel();
        list_selected_columns.setModel(list2Model);
    }//GEN-LAST:event_combo_dbtablesItemStateChanged
    
    private void btn_DBconnectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_DBconnectActionPerformed
        
        comboBoxModel = new DefaultComboBoxModel();
        combo_dbtables.setModel(comboBoxModel);
        
        /**********Filling Bean***********/
        connDB = ConnectDB.getIntance();
        connDB.setLocalhost(txt_hostname.getText().toString().trim());
        connDB.setDbname(txt_dbname.getText().toString().trim());
        connDB.setDbport(txt_dbport.getText().toString().trim());
        connDB.setDbusrname(txt_dbusername.getText().toString().trim());
        connDB.setDbpaswrd(txt_dbpassword.getText());
        
        dsDataHolder = new DataSourceDataHolder();
        dsDataHolder.setDatabaseName(connDB.getDbname());
        dsDataHolder.setHostName(connDB.getLocalhost());
        dsDataHolder.setDriverClassName("com.mysql.jdbc.Driver");
        dsDataHolder.setUrl("jdbc:mysql://" + connDB.getLocalhost() + "/" + connDB.getDbname());
        dsDataHolder.setUsername(connDB.getDbusrname());
        dsDataHolder.setPassword(connDB.getDbpaswrd());
        
        dbmetadata = new com.jwag.db.DatabaseMetaData();
        
        try {
            
            List<String> table = dbmetadata.getTablesName();
            int j = 0;
            
            for (String tablename : table) {
                
                comboBoxModel.addElement(tablename);
            }
            
            btn_DBconnect.setEnabled(false);
            jTAMessages.setText("Connecting... Connection Build Successfully");
            
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Provided Connection Details is Wrong \n Check your Details","Error",JOptionPane.INFORMATION_MESSAGE);
            jTAMessages.setText("");
            System.out.println("Exception in Loading Table : " + ex.getMessage() + " " + " " + ex.getCause());
            
        }
    }//GEN-LAST:event_btn_DBconnectActionPerformed
    
    public static void main(String[] args) {
        
        //ImageIcon icon = createImageIcon("/images/jwagLogo.jpg","a pretty but meaningless splat");
        //jLabel13 = new JLabel("Java Technology Dive Log", new ImageIcon(path), JLabel.CENTER);
        java.awt.EventQueue.invokeLater(new Runnable() {
            
            public void run() {
                
                JwagMain jwag = new JwagMain();
                jwag.setDefaultLookAndFeelDecorated(true);
                jwag.setResizable(false);
                jwag.setVisible(true);
            }
        });
    }
    
    public void setTextFieldsEditable(boolean action) {
        
        txt_hostname.setEditable(action);
        txt_dbname.setEditable(action);
        txt_dbport.setEditable(action);
        txt_dbusername.setEditable(action);
        txt_dbpassword.setEditable(action);
        btn_DBconnect.setEnabled(action);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGenerator;
    private javax.swing.JButton btn_DBconnect;
    private javax.swing.JButton btn_add;
    private javax.swing.JButton btn_addall;
    private javax.swing.JButton btn_close;
    private javax.swing.JButton btn_disconnect;
    private javax.swing.JButton btn_remove;
    private javax.swing.JButton btn_removeall;
    public javax.swing.JComboBox combo_dbtables;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu10;
    private javax.swing.JMenu jMenu11;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuBar jMenuBar3;
    private javax.swing.JMenuBar jMenuBar4;
    private javax.swing.JMenuBar jMenuBar5;
    private javax.swing.JMenuBar jMenuBar6;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator14;
    private javax.swing.JSeparator jSeparator15;
    private javax.swing.JSeparator jSeparator16;
    private javax.swing.JSeparator jSeparator18;
    private javax.swing.JSeparator jSeparator19;
    private javax.swing.JSeparator jSeparator20;
    private javax.swing.JSeparator jSeparator21;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JTextArea jTAMessages;
    public javax.swing.JList list_all_columns;
    public javax.swing.JList list_selected_columns;
    private javax.swing.JRadioButtonMenuItem metaradiobutton1;
    private javax.swing.JRadioButtonMenuItem metaradiobutton2;
    private javax.swing.JRadioButtonMenuItem metaradiobutton3;
    private javax.swing.JRadioButtonMenuItem metaradiobutton4;
    private javax.swing.JRadioButtonMenuItem motifradiobutton1;
    private javax.swing.JRadioButtonMenuItem motifradiobutton2;
    private javax.swing.JRadioButtonMenuItem motifradiobutton3;
    private javax.swing.JRadioButtonMenuItem motifradiobutton4;
    private javax.swing.JTextField txtAppName;
    private javax.swing.JTextField txt_dbname;
    private javax.swing.JPasswordField txt_dbpassword;
    private javax.swing.JTextField txt_dbport;
    private javax.swing.JTextField txt_dbusername;
    public javax.swing.JTextField txt_hostname;
    private javax.swing.JTextField txt_packagename;
    private javax.swing.JRadioButtonMenuItem windowClassic1;
    private javax.swing.JRadioButtonMenuItem windowClassic2;
    private javax.swing.JRadioButtonMenuItem windowClassic3;
    private javax.swing.JRadioButtonMenuItem windowClassic4;
    private javax.swing.JRadioButtonMenuItem windowsradiobutton1;
    private javax.swing.JRadioButtonMenuItem windowsradiobutton2;
    private javax.swing.JRadioButtonMenuItem windowsradiobutton3;
    private javax.swing.JRadioButtonMenuItem windowsradiobutton4;
    // End of variables declaration//GEN-END:variables
    private DefaultListModel listModel;
    private DefaultListModel list2Model;
    private DefaultComboBoxModel comboBoxModel;
    private JFrame frame;
    private com.jwag.db.DatabaseMetaData dbmetadata;
    private ArrayList table_names;
    private ArrayList column_metadata;
    private ConnectDB connDB;
    private DataSourceDataHolder dsDataHolder;
    private ApplicationContextGenerator applicationContextGen;
    private String projectPackage;
    private String path = "";
    /* Static Varible Declaration */
    public static String applicationName;
    public static String tableName;
    public static List<String> columnNames;
}